/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_HelloJni */

#ifndef _Included_org_example_HelloJni
#define _Included_org_example_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_HelloJni
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_HelloJni_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
